### ISSUE TITLE
Only the submitted line is parroted when a word isn't the end of the line

### ISSUE THREAD

**Issue by exchgr** [exchgr/SlamWhale#1]
When anything other than a hashtag or punctuation is at the end of a line, SlamWhale simply returns the line without any poetry. Examples that fail are spaces and numbers. Bilal mentioned that there may be a way to automatically convert a number to its spelling.

**Comment by bilalq** [comment]
For spaces, there is an easy fix. We can use a trim function: http://php.net/manual/en/function.trim.php

Here's an example of how it'd work (using java as an example):
String phrase = "   Hello world, come see my rhymes     ";
phrase = phrase.trim();

phrase would then equal: "Hello world, come see my rhymes"

**Comment by exchgr** [comment]
Go ahead and put it in.

**Comment by bilalq** [comment]
Are we using rhyme or rhyme new?
