### ISSUE TITLE
Move slamwhale.com to heroku app

### ISSUE THREAD

**Issue by x** [exchgr/SlamWhale#15]
I honestly have no idea where slamwhale is currently hosted, but I have the new one on a free heroku instance hitting a free 500mb mongohq mongo replica here: http://afternoon-badlands-4624.herokuapp.com/

Reasons to keep it here:
- We can all deploy
- No single one of us needs to maintain the hosting
- No database worries
- IT'S FREE

What we would need to do:
- I need to give you guys access to the heroku app
- @exchgr (I think he owns the domain?) needs to update the DNS record

@exchgr @bilalq @MrJaeger 
Does this sound good to you guys?

**Comment by bilalq** [comment]
I actually own the domain. Give me access and I'll take care of the transfer.

**Comment by exchgr** [comment]
Sounds good to me.

**Comment by exchgr** [comment]
Mind if I rename the Heroku app to "slamwhale" and link it to this GitHub repo?

**Comment by x** [comment]
sure thing, go for it

## 

Devon Peticolas
twitter: @dproi | web: http://peticol.as

**Comment by bilalq** [comment]
Ugh... Heroku doesn't provide DNS services. I could use my Linode or Route 53 for this, I suppose. I'll get around to this at some point.

**Comment by x** [comment]
The issue I've run into with pointing to heroku in the past is that you need to use a cname, and most DNS providers don't provide that at the apex level.

whois tells me slamwhale's DNS is GoDaddy? It looks like they offer a redirect service for apex domains to subdomains. I'd just go with that and keep it on heroku. One of us could just host a 301 redirect ourselves, but I'd rather take infrastructure off our plates completely.

**Comment by exchgr** [comment]
My feelings:
- We shouldn't be using GoDaddy, because they're depraved.
- Namecheap and Hover, two excellent registrars, offer CNAME support. Let's go with one of them.

**Comment by x** [comment]
@bilalq any update on this?

**Comment by x** [comment]
@bilalq any update on this?

**Comment by x** [comment]
@bilalq any update on this?

**Comment by bilalq** [comment]
I'll look at this tonight.

**Comment by exchgr** [comment]
That was fun: http://inft.ly/3429PNc

**Comment by bilalq** [comment]
For the record, I did try to get us to work together on this when I was visiting the east coast. I'd say I did my part. :-)

**Comment by bilalq** [comment]
Couldn't get to this yet. I'll take care of this in the weekend.

**Comment by x** [comment]
@bilalq any update on this?

**Comment by x** [comment]
@bilalq any update on this?

**Comment by x** [comment]
@bilalq any update on this?

**Comment by x** [comment]
@bilalq any update on this?

**Comment by bilalq** [comment]
I created CNAME and A records using Route53/S3 and updated nameserver listings. Give it 24-48 hours for everything to propagate.

**Comment by exchgr** [comment]
YES
