### ISSUE TITLE
Who has access to slamwhale.com?

### ISSUE THREAD

**Issue by MrJaeger** [exchgr/SlamWhale#20]
Right now slamwhale.com does not work in any way, shape, or form, but http://afternoon-badlands-4624.herokuapp.com/ does in fact seem to work (and i assume is what this repo is based on).  Can someone point to that instead of wherever it is right now?

**Comment by x** [comment]
@bilalq

**Comment by bilalq** [comment]
The domain should point correctly now. Just need to wait for DNS stuff to propagate.
