### ISSUE TITLE
Expansion plans

### ISSUE THREAD

**Issue by bilalq** [exchgr/SlamWhale#6]
Earlier today, we were also talking about some ways to enhance functionality. It'd be cool if we had an option to be able to browse through previously rendered poems the way sites like FML and MLIA allow you to go through entries. We can also have a thumbs up/thumbs down system to rank poems and display in order of popularity.

If we ever do decide to go for accounts, I think it'd be best to go with "Sign in with Twitter". Most people prefer to avoid making new accounts if they can avoid it. This would simplify the process while still allowing for an enriched experience.

I am going to spend this week reading up on php and javascript. I know you guys already vetoed using Rails, but I'd just like to throw in a little plug and remind you guys that Twitter uses Rails as well. Those interested in learning ruby can probably get the basics down in a day using this tutorial: http://pine.fm/LearnToProgram/

**Comment by exchgr** [comment]
Nice ideas. Please split'em up into separate feature requests to make tracking more easy. Once each thing is done, any of us can just hit "Close Issue," as though we were checking off a todo list. There's no way to do that currently.

**Comment by exchgr** [comment]
Or I'll do it...

**Comment by bilalq** [comment]
I'll split them up tomorrow. I really need to finish my homework now. I've procrastinated way too long.

**Comment by exchgr** [comment]
Alright cool

**Comment by bilalq** [comment]
Even now, this sounds kinda cool. Probably unnecessary though. I'll leave the issue open for now.

**Comment by bilalq** [comment]
Actually, upon further reflection, I realize that it's kind of pointless.
